/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import business.VendaBS;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.PagamentoModel;

/**
 *
 * @author IBBN
 */
public class HistoricoPagamento extends javax.swing.JFrame {
       VendaBS vendaBs= new VendaBS();
       Iterator  itVendas  = null;
    /**
     * Creates new form HistoricoPagamento
     */
    public HistoricoPagamento() {
        initComponents();
        setSize(679, 593);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextHp = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Histórico de Pagamentos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(193, 11, 263, 29);

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));
        jPanel3.setForeground(new java.awt.Color(238, 238, 34));

        jTextHp.setColumns(20);
        jTextHp.setRows(5);
        jTextHp.setEnabled(false);
        jScrollPane1.setViewportView(jTextHp);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(17, 54, 650, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        jTextHp.setText("");
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoricoPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoricoPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoricoPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoricoPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoricoPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextHp;
    // End of variables declaration//GEN-END:variables
    public void  CarregarHistorico(int CodVenda){
        jTextHp.setText("");
       try {
               itVendas = vendaBs.ObterHistoricoPagamentoCliente(CodVenda);
                ListaHistoricodeVenda(itVendas);
           } catch (Exception ex) {
               Logger.getLogger(HistoricoPagamento.class.getName()).log(Level.SEVERE, null, ex);
           }
    }
    private void ListaHistoricodeVenda(Iterator itVendas) {
        
         int count=1;
         while (itVendas.hasNext()) {
              PagamentoModel auxHp = (PagamentoModel) itVendas.next();
         String Historico = "_____________________________PAGAMENTO_"+count+"________________________________\n"+
                            "                                                                                \n"+
                            "          DATA VENDA : "+auxHp.getDataVenda()+"            ÚLTIMO PAGAMENTO: "+auxHp.getUltimoPagamento()+"                      \n"+
                            "                                                                                \n"+
                            "DESCRIÇÃO DA COMPRA |  CODIGO | VALOR PRODUTO | VALOR PEDENTE | VALOR PAGO |     \n"+
                            ""+auxHp.getDescCompra()+"                  "+auxHp.getCodigoCompra()+"      R$ "+auxHp.getValorProduto()+"     "
                 + "      R$ "+auxHp.getValorPendente()+"      R$ "+
                            +auxHp.getValorPago()+"\n"+
                            "_________________________________________________________________________________\n";
                 count++;
         jTextHp.append(Historico);
         }
    }
}
