/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import business.VendaBS;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.VendaModel;

/**
 *
 * @author IBBN
 */
public class ListaVendas extends javax.swing.JFrame {
    ListadeVendaCliente exibirvendascliente = new ListadeVendaCliente();
   
    /**
     * Creates new form ListaVendas
     */
    public ListaVendas() {
        initComponents();
        jTextFieldclientecel.setEditable(false);
    }

    public void CarregarGridVenda(String venda, String[] mes) {
      ;
       while (jTableHvendas.getModel().getRowCount() > 0) {  
           ((DefaultTableModel)jTableHvendas.getModel()).removeRow(0);  
       } 
        try {
            DefaultTableModel modelo = (DefaultTableModel) jTableHvendas.getModel();

            Iterator  itVendas  = null;
            VendaBS vendaBS = new VendaBS();
            itVendas = vendaBS.BuscaVendaMes(mes,venda);
           
          
            while ( itVendas.hasNext()) {
                  VendaModel Vendaaux = (VendaModel)   itVendas.next();
                modelo.addRow(new String[]{String.valueOf(Vendaaux.getCodVenda()),Vendaaux.getNomeCliente(),
                NumberFormat.getCurrencyInstance().format(Double.parseDouble(Double.toString(Vendaaux.getValorProduto()))),
                NumberFormat.getCurrencyInstance().format(Double.parseDouble(Double.toString(Vendaaux.getValorEntrada()))),
                NumberFormat.getCurrencyInstance().format(Double.parseDouble(Double.toString(Vendaaux.getValorPedente()))),
                Vendaaux.getHoraDaVenda(),Vendaaux.getFormaPgmt(), Vendaaux.getDescricaoCompra()});
            }
            
            
               itVendas.remove();
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Aprazo = new javax.swing.JRadioButton();
        Avista = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHvendas = new javax.swing.JTable();
        jLabelcli1 = new javax.swing.JLabel();
        jTextFieldclientecel = new javax.swing.JTextField();
        jCalendar2 = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Historico de Vendas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        buttonGroup1.add(Aprazo);
        Aprazo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Aprazo.setText("Lista de Vendas A Prazo");
        Aprazo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AprazoMouseClicked(evt);
            }
        });

        buttonGroup1.add(Avista);
        Avista.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Avista.setText("Lista de Vendas A Vista");
        Avista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AvistaMouseClicked(evt);
            }
        });

        jTableHvendas.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTableHvendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cliente", "Valor Produto", "Valor Entrada", "Pendente", "Data da Venda", "Forma de Pagamento", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableHvendas);

        jLabelcli1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelcli1.setText("Cliente selecionado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelcli1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Aprazo)
                        .addGap(18, 18, 18)
                        .addComponent(Avista))
                    .addComponent(jTextFieldclientecel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldclientecel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelcli1))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Aprazo)
                            .addComponent(Avista))
                        .addGap(4, 4, 4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AprazoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AprazoMouseClicked
        // TODO add your handling code here:
          String[] datas = ObterPrimeiroUltimoDIaDoMesPorDataJcalendar();
            jLabelcli1.setText("Cliente :");
            jTextFieldclientecel.setText("");
            String mes = String.valueOf(jCalendar2.getDate());
            CarregarGridVenda("A Prazo", datas);
    }//GEN-LAST:event_AprazoMouseClicked

    private void AvistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AvistaMouseClicked
        // TODO add your handling code here:
         String[] datas = ObterPrimeiroUltimoDIaDoMesPorDataJcalendar();
        jLabelcli1.setText("Código :");
        jTextFieldclientecel.setText("");
        jTextFieldclientecel.setText("");
        String mes = String.valueOf(jCalendar2.getDate());
        CarregarGridVenda("A Vista",datas);
    }//GEN-LAST:event_AvistaMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        exibirvendascliente.dispose();
    }//GEN-LAST:event_formWindowClosed

    public String[] ObterPrimeiroUltimoDIaDoMesPorDataJcalendar(){
       String[] ArrayData = new String[2];
       
        SimpleDateFormat sdfJcalendar = new SimpleDateFormat("M");
        SimpleDateFormat dia = new SimpleDateFormat("YYYY-MM-dd");
       
                Calendar dataAtual = Calendar.getInstance();
		Calendar primeiroDia = Calendar.getInstance();
		Calendar ultimoDia = Calendar.getInstance();
		//1º dia do mês atual
                String MesSelectCalendario = sdfJcalendar.format(jCalendar2.getDate());
                
                primeiroDia.add(Calendar.MONTH,Integer.parseInt(MesSelectCalendario)-2);
		primeiroDia.add(Calendar.DAY_OF_MONTH, -dataAtual.get(Calendar.DAY_OF_MONTH));
		primeiroDia.add(Calendar.DAY_OF_YEAR, 1);
                
		//Ultimo dia do mês atual
		ultimoDia.add(Calendar.MONTH, Integer.parseInt(MesSelectCalendario)-1);
		ultimoDia.add(Calendar.DAY_OF_MONTH, -dataAtual.get(Calendar.DAY_OF_MONTH));
		//System.out.println(ultimoDia.getTime());
                
       SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
       ArrayData[0] = sdf.format(primeiroDia.getTime());
       ArrayData[1] = sdf.format(ultimoDia.getTime());
       
       return ArrayData;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Aprazo;
    private javax.swing.JRadioButton Avista;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabelcli1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableHvendas;
    private javax.swing.JTextField jTextFieldclientecel;
    // End of variables declaration//GEN-END:variables
}
