/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import business.VendaBS;
import java.text.NumberFormat;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import modelo.VendaModel;
import business.JtextFieldSomenteNumeros;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
/**
 *
 * @author IBBN
 */
public class ListadeVendaCliente extends javax.swing.JFrame {
   VendaBS updatevenda = new VendaBS();
   VendaModel upVenda  = new  VendaModel();
   double ValorEntrada =0;
   String codCliente;
   String codVenda=null;
   DateFormat formatterPadrao = new SimpleDateFormat("dd/MM/yyyy");
   DateFormat df = DateFormat.getDateInstance(DateFormat.FULL,new Locale("pt","br"));
    HistoricoPagamento AbrirHp = new HistoricoPagamento();
  
    /**
     * Creates new form ListadeVendaCliente
     */
    public ListadeVendaCliente() {
        initComponents();
        jTextFieldPagamento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jButtExcluirCompra.setEnabled(false);
    }
    
  public void CarregarGridVenda(String venda, String codCli) {
     
         codCliente = codCli;      
       while (jTableclienteVenda.getModel().getRowCount() > 0) {  
           ((DefaultTableModel)jTableclienteVenda.getModel()).removeRow(0);  
      }
      try {
          DefaultTableModel modelo = (DefaultTableModel) jTableclienteVenda.getModel();
          Iterator itVendas = null;
          VendaBS vendaBS = new VendaBS();
          itVendas = vendaBS.ListaVendas(venda);
          double total = 0;
          while (itVendas.hasNext()) {

              VendaModel Vendaaux = (VendaModel) itVendas.next();
              total += Vendaaux.getValorPedente();
              Date datePadrao = (Date) formatterPadrao.parse(Vendaaux.getHoraDaVenda());
              modelo.addRow(new String[]{String.valueOf(Vendaaux.getCodVenda()), Vendaaux.getDescricaoCompra(),
                  NumberFormat.getCurrencyInstance().format(Double.parseDouble(Double.toString(Vendaaux.getValorProduto()))),
                  NumberFormat.getCurrencyInstance().format(Double.parseDouble(Double.toString(Vendaaux.getValorEntrada()))),
                  NumberFormat.getCurrencyInstance().format(Double.parseDouble(Double.toString(Vendaaux.getValorPedente()))),
                  Vendaaux.getDatadaVenda(), df.format(datePadrao), Vendaaux.getFormaPgmt()});

          }
          jLabelCliente1.setText(venda);
          jlabeltotal.setText(NumberFormat.getCurrencyInstance().format(total));
          itVendas.remove();
        } catch (Exception e) {
             
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableclienteVenda = new javax.swing.JTable();
        jlabelpendente = new javax.swing.JLabel();
        jLabelCliente1 = new javax.swing.JLabel();
        jlabeltotal = new javax.swing.JLabel();
        jlabeltotalapagar1 = new javax.swing.JLabel();
        jlabeltotalapagar2 = new javax.swing.JLabel();
        jlabeltotalapagar3 = new javax.swing.JLabel();
        jTextFieldPagamento = new JtextFieldSomenteNumeros();
        jButton1 = new javax.swing.JButton();
        jlabeltotalapagar4 = new javax.swing.JLabel();
        jlabelcódígo = new javax.swing.JLabel();
        jlabelrealpagamento = new javax.swing.JLabel();
        jButtExcluirCompra = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setTitle("Lista de Vendas Cliente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTableclienteVenda.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTableclienteVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descrição", "Valor do Produto", "Valor de Entrada", "Valor Pendente", "Data da Compra", "Data Último Pagamento", "Forma de Pagamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableclienteVenda.setMinimumSize(new java.awt.Dimension(45, 0));
        jTableclienteVenda.setPreferredSize(new java.awt.Dimension(600, 500));
        jTableclienteVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableclienteVendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableclienteVenda);

        jlabelpendente.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jlabelpendente.setForeground(new java.awt.Color(255, 0, 0));
        jlabelpendente.setText("R$");

        jLabelCliente1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelCliente1.setForeground(new java.awt.Color(255, 102, 0));
        jLabelCliente1.setText("Cliente");

        jlabeltotal.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jlabeltotal.setForeground(new java.awt.Color(255, 153, 0));
        jlabeltotal.setText("R$");

        jlabeltotalapagar1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jlabeltotalapagar1.setForeground(new java.awt.Color(255, 0, 0));
        jlabeltotalapagar1.setText("Total Pendente :");

        jlabeltotalapagar2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jlabeltotalapagar2.setForeground(new java.awt.Color(255, 0, 0));
        jlabeltotalapagar2.setText("Valor Pendente Selecionado :");

        jlabeltotalapagar3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jlabeltotalapagar3.setForeground(new java.awt.Color(30, 155, 30));
        jlabeltotalapagar3.setText("Realizar Pagamento :");

        jTextFieldPagamento.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldPagamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPagamentoKeyReleased(evt);
            }
        });

        jButton1.setText("Confirma Pagamento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jlabeltotalapagar4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jlabeltotalapagar4.setText("CÓDIGO:");

        jlabelcódígo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jlabelcódígo.setText("0");

        jlabelrealpagamento.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jlabelrealpagamento.setForeground(new java.awt.Color(103, 186, 42));
        jlabelrealpagamento.setText("R$");

        jButtExcluirCompra.setText("Excluir Compra");
        jButtExcluirCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtExcluirCompraActionPerformed(evt);
            }
        });

        jMenu2.setText("Pagamentos");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem1.setText("Histórico de Pagamentos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 992, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlabeltotalapagar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlabelpendente)
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlabeltotalapagar4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlabelcódígo))
                            .addComponent(jlabeltotalapagar3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlabelrealpagamento))
                            .addComponent(jButtExcluirCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlabeltotalapagar1)
                                .addGap(18, 18, 18)
                                .addComponent(jlabeltotal))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(29, 29, 29))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabelCliente1)
                    .addContainerGap(930, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabeltotalapagar4)
                    .addComponent(jlabelcódígo)
                    .addComponent(jButtExcluirCompra)
                    .addComponent(jlabeltotalapagar1)
                    .addComponent(jlabeltotal))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabeltotalapagar2)
                            .addComponent(jlabeltotalapagar3)
                            .addComponent(jTextFieldPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelpendente)
                            .addComponent(jlabelrealpagamento)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabelCliente1)
                    .addContainerGap(531, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableclienteVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableclienteVendaMouseClicked
        // TODO add your handling code here:
        try{
              
       
         if(jTableclienteVenda.getModel().getRowCount() > 0) {
        jlabelpendente.setText((String) jTableclienteVenda.getModel().getValueAt(jTableclienteVenda.getSelectedRow(),4));
        jlabelcódígo.setText((String) jTableclienteVenda.getModel().getValueAt(jTableclienteVenda.getSelectedRow(),0));
        codVenda =(String) jTableclienteVenda.getModel().getValueAt(jTableclienteVenda.getSelectedRow(),0);
        jButtExcluirCompra.setEnabled(true);
        String total = (String) jTableclienteVenda.getModel().getValueAt(jTableclienteVenda.getSelectedRow(),3);
        total = total.substring(2);
        total = total.replaceAll(",", ".");
        ValorEntrada = Double.parseDouble(total);
        }
        }catch(Exception e){}
       
    }//GEN-LAST:event_jTableclienteVendaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String total = jlabelpendente.getText();
        total = total.substring(2);
        total = total.replaceAll(",", ".");
        if (total.equals("")) {
            JOptionPane.showMessageDialog(this, "Selecione uma Venda Para Pagamento!");
        }
        if (jTextFieldPagamento.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite o Valor de Pagamento!");

        }
        if (!jTextFieldPagamento.getText().equals("") && !total.equals("")) {
            try{
            double Pagamento = Double.parseDouble(jTextFieldPagamento.getText());
            if (Pagamento > Double.parseDouble(total)) {
                JOptionPane.showMessageDialog(this, "Valor de Pagamento, " + Pagamento + " Maior que Valor Pendente, " + total + ". \n"
                        + "Digite um Valor Menor ou igual a Valor Pendente.");
            }else{   upVenda.setValorEntrada(Pagamento+ValorEntrada);
                     upVenda.setValorPedente(Double.parseDouble(total)-Pagamento);
                     upVenda.setCodVenda(Integer.parseInt(jlabelcódígo.getText()));
                     updatevenda.vendaupdate(upVenda,Pagamento,Double.parseDouble(total));
                     JOptionPane.showMessageDialog(this,upVenda.getMesagem());
                     CarregarGridVenda(jLabelCliente1.getText(),null);
                     
                     limpar();
            }
            
            }catch(Exception e){
             JOptionPane.showMessageDialog(this,"Erro no Sistema"+ e);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldPagamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPagamentoKeyReleased
        // TODO add your handling code here:
         String format = "R$";
         try{
        if(!jTextFieldPagamento.getText().equals("")){
          format =   NumberFormat.getCurrencyInstance().format(Double.parseDouble(jTextFieldPagamento.getText()));
          jlabelrealpagamento.setText(format); 
        }else{
           jlabelrealpagamento.setText("R$");
        }
         }catch(Exception e){
              jlabelrealpagamento.setText(format);
            }
      
    }//GEN-LAST:event_jTextFieldPagamentoKeyReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        codVenda =null;
        limpar();
    }//GEN-LAST:event_formWindowClosed

    private void jButtExcluirCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtExcluirCompraActionPerformed
        // TODO add your handling code here:
        VendaBS excluirVenda = new VendaBS();
        VendaModel ex = new VendaModel();
         if(codVenda==null){JOptionPane.showMessageDialog(this, "Selecione uma Compra com Duplo Clique!");}else{
         try {
           ex.setCodVenda(Integer.parseInt(codVenda));
           excluirVenda.Excluirvenda(ex);
           CarregarGridVenda(jLabelCliente1.getText(),null);
           JOptionPane.showMessageDialog(this, ex.getMesagem());
           CarregarGridVenda(jLabelCliente1.getText(),null);
       } catch (Exception ex1) {
             JOptionPane.showMessageDialog(this, "Erro ao ExCluir Venda"+ex1);
       }
         
         }
      
    }//GEN-LAST:event_jButtExcluirCompraActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
            codVenda =null;
            jButtExcluirCompra.setEnabled(false);
            limpar();
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         AbrirHp.setVisible(true);
         AbrirHp.setAlwaysOnTop(true);
         if(codCliente!=null){
         AbrirHp.CarregarHistorico(Integer.parseInt(codCliente));
         }
         
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadeVendaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadeVendaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadeVendaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadeVendaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListadeVendaCliente().setVisible(true);
            }
        });
    }
    
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtExcluirCompra;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelCliente1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableclienteVenda;
    public javax.swing.JTextField jTextFieldPagamento;
    private javax.swing.JLabel jlabelcódígo;
    private javax.swing.JLabel jlabelpendente;
    private javax.swing.JLabel jlabelrealpagamento;
    private javax.swing.JLabel jlabeltotal;
    private javax.swing.JLabel jlabeltotalapagar1;
    private javax.swing.JLabel jlabeltotalapagar2;
    private javax.swing.JLabel jlabeltotalapagar3;
    private javax.swing.JLabel jlabeltotalapagar4;
    // End of variables declaration//GEN-END:variables

public void limpar(){
  jlabelcódígo.setText("");
  jlabelpendente.setText("R$");
  jTextFieldPagamento.setText("");
  jlabelrealpagamento.setText("R$");
}
}
