/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import business.JtextFieldSomenteNumeros;
import business.VendaBS;
import java.text.NumberFormat;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import modelo.TimerToLabel;
import modelo.VendaModel;

/**
 *
 * @author IBBN
 */
public class Venda extends javax.swing.JFrame {
   ListadeClientes viewlistaCliente = new ListadeClientes();
   VendaModel novaVenda = new  VendaModel();
   VendaBS vendaBS = new VendaBS();
   TimerToLabel TimeLabel;
    /**
     * Creates new form Venda
     */
    public Venda(){
        initComponents();
         jPanel1.setVisible(false);
         ValorVendaPrazo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
         jtextValorProduto1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
         ValorVendaPrazo.setText("0");
         jtextValorProduto1.setText("0");
       
    }

    public boolean ValidaVenda(){
        if (Avista.isSelected()) {
            if (jtextValorProduto1.getText().equals("") || ValorVendaPrazo.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Valor do Produto e Entrada não pode Esta Vazio");
            } else {
                novaVenda.setCodCliente(0);
                novaVenda.setValorProduto(Double.parseDouble(jtextValorProduto1.getText()));
                novaVenda.setValorEntrada(Double.parseDouble(ValorVendaPrazo.getText()));
                novaVenda.setDescricaoCompra(jTextFieldDescricao.getText());
                novaVenda.setFormaPgmt("A Vista");
                return true;
            }
        }
        if (Aprazo.isSelected()) {
            if (jtextValorProduto1.getText().equals("") || ValorVendaPrazo.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Valor do Produto e Entrada não pode Esta Vazio");
            }
            if (viewlistaCliente.idClienteSelecionado == null) {
                JOptionPane.showMessageDialog(this, "Selecione um Cliente");
            }
            if (!jtextValorProduto1.getText().equals("") && !ValorVendaPrazo.getText().equals("") && viewlistaCliente.idClienteSelecionado != null) {
                novaVenda.setCodCliente(Integer.parseInt(viewlistaCliente.idClienteSelecionado));
                novaVenda.setValorProduto(Double.parseDouble(jtextValorProduto1.getText()));
                novaVenda.setValorEntrada(Double.parseDouble(ValorVendaPrazo.getText()));
                novaVenda.setDescricaoCompra(jTextFieldDescricao.getText());
                novaVenda.setFormaPgmt("A Prazo");
                novaVenda.setValorPedente(Double.parseDouble(jtextValorProduto1.getText())-Double.parseDouble(ValorVendaPrazo.getText()));
                return true;
            }
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup6 = new javax.swing.ButtonGroup();
        Avista = new javax.swing.JRadioButton();
        Aprazo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        LabelSelecionaCliente = new javax.swing.JLabel();
        mensagemCliente = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ButtonBuscaCliente = new javax.swing.JButton();
        RealConvertido = new javax.swing.JLabel();
        LabelProduto = new javax.swing.JLabel();
        labelProdutoReal = new javax.swing.JLabel();
        jtextValorProduto1 = new JtextFieldSomenteNumeros();
        ValorVendaPrazo = new JtextFieldSomenteNumeros();
        jLabelVendaTotalpagarTroco = new javax.swing.JLabel();
        jLabeltotalapagar = new javax.swing.JLabel();
        labeltrocoreal = new javax.swing.JLabel();
        labeltroco1 = new javax.swing.JLabel();
        LabelSelecionaCliente1 = new javax.swing.JLabel();
        jTextFieldDescricao = new javax.swing.JTextField();
        clienteSelect = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda ");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        buttonGroup6.add(Avista);
        Avista.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Avista.setText("A vista");
        Avista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvistaActionPerformed(evt);
            }
        });

        buttonGroup6.add(Aprazo);
        Aprazo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Aprazo.setText("A prazo");
        Aprazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AprazoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("Seleciona a forma de Pagamento");

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jButton1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton1.setText("Finalizar Venda ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LabelSelecionaCliente.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LabelSelecionaCliente.setText("Selecionar Cliente :");

        mensagemCliente.setForeground(new java.awt.Color(255, 0, 0));
        mensagemCliente.setText("Caso o cliente não esteja na lista  realize o Cadastro do Cliente");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel5.setText("Entrada:");

        ButtonBuscaCliente.setText("Selecionar Cliente...");
        ButtonBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscaClienteActionPerformed(evt);
            }
        });

        RealConvertido.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        RealConvertido.setForeground(new java.awt.Color(98, 163, 54));
        RealConvertido.setText("R$ 0,00");
        RealConvertido.setToolTipText("");

        LabelProduto.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        LabelProduto.setText("Valor Produto:");

        labelProdutoReal.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        labelProdutoReal.setForeground(new java.awt.Color(255, 0, 0));
        labelProdutoReal.setText("R$ 0,00");
        labelProdutoReal.setToolTipText("");

        jtextValorProduto1.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        jtextValorProduto1.setForeground(new java.awt.Color(255, 0, 0));
        jtextValorProduto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtextValorProduto1KeyReleased(evt);
            }
        });

        ValorVendaPrazo.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        ValorVendaPrazo.setForeground(new java.awt.Color(98, 163, 54));
        ValorVendaPrazo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ValorVendaPrazoKeyReleased(evt);
            }
        });

        jLabelVendaTotalpagarTroco.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabelVendaTotalpagarTroco.setText("Total a Pagar :");

        jLabeltotalapagar.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabeltotalapagar.setForeground(new java.awt.Color(255, 0, 0));
        jLabeltotalapagar.setToolTipText("");

        labeltrocoreal.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        labeltrocoreal.setForeground(new java.awt.Color(0, 51, 204));

        labeltroco1.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        labeltroco1.setText("Troco :");

        LabelSelecionaCliente1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LabelSelecionaCliente1.setText("Descrição :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelProduto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelSelecionaCliente1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelSelecionaCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(jtextValorProduto1)
                            .addComponent(ButtonBuscaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ValorVendaPrazo)
                            .addComponent(jTextFieldDescricao))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelProdutoReal, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RealConvertido, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabeltotalapagar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelVendaTotalpagarTroco)
                                    .addComponent(labeltroco1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(labeltrocoreal))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(clienteSelect)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(mensagemCliente)
                        .addGap(199, 199, 199))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensagemCliente)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSelecionaCliente)
                    .addComponent(ButtonBuscaCliente)
                    .addComponent(clienteSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelSelecionaCliente1)
                    .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtextValorProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelProduto)
                            .addComponent(labelProdutoReal, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ValorVendaPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RealConvertido, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelVendaTotalpagarTroco)
                        .addGap(18, 18, 18)
                        .addComponent(jLabeltotalapagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labeltroco1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labeltrocoreal)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(Avista)
                .addGap(52, 52, 52)
                .addComponent(Aprazo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(220, 220, 220))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aprazo)
                    .addComponent(Avista))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscaClienteActionPerformed
        // TODO add your handling code here:
  
       viewlistaCliente.setVisible(true);
       viewlistaCliente.setAlwaysOnTop(true); 
       viewlistaCliente.jButtonExlcuir.setVisible(false);

       if(viewlistaCliente.jTable1.getRowCount()!=0){
       viewlistaCliente.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
       
       }
       
       viewlistaCliente.jButtonSelecionarCliente.setVisible(true);
       if(TimeLabel == null){ TimeLabel = ObterCliente(clienteSelect, viewlistaCliente);}
    }//GEN-LAST:event_ButtonBuscaClienteActionPerformed

   private TimerToLabel ObterCliente(JLabel cliente,  ListadeClientes listaCliente){
      
       final TimerToLabel timer = new TimerToLabel(1000, cliente,listaCliente);
       timer.init();
       return timer;
   }
    private void AprazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AprazoActionPerformed
        // TODO add your handling code here:
       ButtonBuscaCliente.setVisible(true);
       mensagemCliente.setVisible(true);
       LabelSelecionaCliente.setVisible(true);
       jLabelVendaTotalpagarTroco.setText("Total a Pagar: ");
       jPanel1.setVisible(true);
    }//GEN-LAST:event_AprazoActionPerformed

    private void AvistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvistaActionPerformed
        // TODO add your handling code here:
       ButtonBuscaCliente.setVisible(false);
       mensagemCliente.setVisible(false);
       LabelSelecionaCliente.setVisible(false);
       jLabelVendaTotalpagarTroco.setText("Total a Pagar: ");
       jPanel1.setVisible(true);
       clienteSelect.setText("");
       if(TimeLabel!=null){
       TimeLabel.stop();
       TimeLabel = null;
       viewlistaCliente.idClienteSelecionado = null;
       viewlistaCliente.ClienteSelecionado = null;
       viewlistaCliente.dispose();
       }
    }//GEN-LAST:event_AvistaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // TODO add your handling code here:
       
        boolean valida;
        int dialogResult;
        valida = ValidaVenda();
        if (valida == true) {
            if(Avista.isSelected()){
                
                dialogResult = JOptionPane.showConfirmDialog(this,
                     "\nDescrição: "+ novaVenda.getDescricaoCompra()
                    +"\nValor Produto  R$: "+ novaVenda.getValorProduto()
                    +"\nValor Entrada  R$: "+ novaVenda.getValorEntrada()
                    +"\nConfirma a Venda ?", "Confirmação de Venda " +novaVenda.getFormaPgmt(), JOptionPane.YES_NO_OPTION);

                 if(novaVenda.getValorEntrada()< novaVenda.getValorProduto()){
                 JOptionPane.showMessageDialog(this, "Valor de Entrada Menor que do Produto, Realize uma Venda A Prazo!");
                 dialogResult = JOptionPane.NO_OPTION;
                 JOptionPane.showMessageDialog(this, "Venda Cancelada.");
                }else{
               
                }
                
            }else{
                
                 dialogResult = JOptionPane.showConfirmDialog(this,"Cliente: "
                     +viewlistaCliente.ClienteSelecionado+
                     "\nDescrição: "+ novaVenda.getDescricaoCompra()
                    +"\nValor Produto  R$: "+ novaVenda.getValorProduto()
                    +"\nValor Entrada  R$: "+ novaVenda.getValorEntrada()
                    +"\nValor Pendente "+ labeltrocoreal.getText()
                    +"\nConfirma a Venda ?", "Confiramação de Venda " +novaVenda.getFormaPgmt(), JOptionPane.YES_NO_OPTION);
                if(novaVenda.getValorEntrada()> novaVenda.getValorProduto()){
                 JOptionPane.showMessageDialog(this, "Valor de Entrada Maior que do Produto, Realize uma Venda A vista!");
                 dialogResult = JOptionPane.NO_OPTION;
                 JOptionPane.showMessageDialog(this, "Venda Cancelada.");
                }else{
               
                }
            }
            
           
            if (dialogResult == JOptionPane.YES_OPTION) {
                try {
                   vendaBS.CadastrarVenda(novaVenda);
                    JOptionPane.showMessageDialog(this,novaVenda.getMesagem());
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this,"Erro"+ ex);
                }
                limpar();
            } else {
                
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtextValorProduto1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtextValorProduto1KeyReleased
        // TODO add your handling code here:
         String format = "R$ 0,00";
         String formattotal = "R$ 0,00";
         
          try {
             
             format =   NumberFormat.getCurrencyInstance().format(Double.parseDouble(jtextValorProduto1.getText()));
             labelProdutoReal.setText(format);
             double total = Double.parseDouble(jtextValorProduto1.getText())- Double.parseDouble(ValorVendaPrazo.getText());
             formattotal =   NumberFormat.getCurrencyInstance().format(Double.parseDouble(Double.toString(total)));
             if(!ValorVendaPrazo.getText().equals("0")){
              labeltrocoreal.setText(formattotal);
              }
            if(total > 0){
             labeltroco1.setText("Pendente: ");
             }else{
              labeltroco1.setText("Troco: ");
             }
        } catch (Exception e) {
            labelProdutoReal.setText("R$ "+jtextValorProduto1.getText());
            jLabeltotalapagar.setText(labelProdutoReal.getText()); labeltrocoreal.setText(ValorVendaPrazo.getText());
            
        }
    }//GEN-LAST:event_jtextValorProduto1KeyReleased

    private void ValorVendaPrazoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorVendaPrazoKeyReleased
        // TODO add your handling code here:
        String format = "R$ 0,00";
          try {
            
              format =   NumberFormat.getCurrencyInstance().format(Double.parseDouble(ValorVendaPrazo.getText()));
              RealConvertido.setText(format);
              double total = Double.parseDouble(jtextValorProduto1.getText()) - Double.parseDouble(ValorVendaPrazo.getText());
              String  formattotal =   NumberFormat.getCurrencyInstance().format(Double.parseDouble(Double.toString(total)));
              if(!ValorVendaPrazo.getText().equals("0")){
              labeltrocoreal.setText(formattotal);
              }
             if(total> 0){
             labeltroco1.setText("Pendente: ");
             }else{
              labeltroco1.setText("Troco: ");
             }
              jLabeltotalapagar.setText(labelProdutoReal.getText());
              
        } catch (Exception e) {
            RealConvertido.setText("R$ "+ValorVendaPrazo.getText());
            jLabeltotalapagar.setText(labelProdutoReal.getText());
            labeltrocoreal.setText(ValorVendaPrazo.getText());
        }
    }//GEN-LAST:event_ValorVendaPrazoKeyReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        viewlistaCliente.idClienteSelecionado = null;
        viewlistaCliente.ClienteSelecionado = null;
        viewlistaCliente.dispose();
        limpar();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venda().setVisible(true);
            }
        });
    }
    
   public void limpar(){
                viewlistaCliente.idClienteSelecionado = null;
                jtextValorProduto1.setText("");
                ValorVendaPrazo.setText("");
                
                jTextFieldDescricao.setText("");
                labelProdutoReal.setText("R$ 0,00");
                RealConvertido.setText("R$ 0,00");
                labeltrocoreal.setText("R$ 0,00");
                jLabeltotalapagar.setText("R$ 0,00");
                clienteSelect.setText("");
                
              if(TimeLabel != null){
                 TimeLabel.stop();
                 TimeLabel = null;
                }
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Aprazo;
    private javax.swing.JRadioButton Avista;
    private javax.swing.JButton ButtonBuscaCliente;
    private javax.swing.JLabel LabelProduto;
    private javax.swing.JLabel LabelSelecionaCliente;
    private javax.swing.JLabel LabelSelecionaCliente1;
    private javax.swing.JLabel RealConvertido;
    public javax.swing.JTextField ValorVendaPrazo;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel clienteSelect;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelVendaTotalpagarTroco;
    public javax.swing.JLabel jLabeltotalapagar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldDescricao;
    public javax.swing.JTextField jtextValorProduto1;
    private javax.swing.JLabel labelProdutoReal;
    private javax.swing.JLabel labeltroco1;
    private javax.swing.JLabel labeltrocoreal;
    private javax.swing.JLabel mensagemCliente;
    // End of variables declaration//GEN-END:variables
}
